### PR TITLE
Update NATTEN context flags

### PR DESCRIPTION
**Pull request by alihassanijr**
enable_fused_na, disable_fused_na -> use_fused_na(True), use_fused_na(False)

enable_autotuner, disable_autotuner -> use_autotuner(True, True), use_autotuner(False, False)

For more refer to:
* https://github.com/SHI-Labs/NATTEN/blob/main/docs/fna/fna-quickstart.md
* https://github.com/SHI-Labs/NATTEN/blob/main/docs/fna/autotuner.md

### CODE REVIEW

**Comment by alihassanijr** [comment]
Note: this temporarily addresses #15 , but we need to discuss whether or not and if so how to start using FNA in StyleNAT.

**Comment by justin4ai** [comment]
Thanks for your correction. But I found one more bug - with ```python main.py type=inference```, the following error occurs:

```

Traceback (most recent call last):
  File "/home/justin/workspace/StyleNAT/main.py", line 166, in main
    validate_args(args)
  File "/home/justin/workspace/StyleNAT/main.py", line 80, in validate_args
    if "batch" not in args.inference:
omegaconf.errors.ConfigAttributeError: Missing key inference
    full_key: inference
    object_type=dict

```

I'm doing some investigation. And seemingly it's because the hydra decorator is changing the value of ,,type''key to inference in config.yaml file according to ```type=inference``` argument in my command line.

But I guess what you wanted to do is to select inference.yaml for the ```config_name``` parameter in hydra.main decorator such that you fetch args from it, not to change the value of ,,type'' key in config.yaml from train into inference.

```python

@hydra.main(version_base=None, config_path="conf", config_name="config")
def main(args):
    print(f"config.yaml loaded. We expect this to be ,,train'' : {args.type}")
    if "logging_level" in args:
        if type(args.logging_level) == str:
            _logging_level = {"DEBUG": logging.DEBUG, "INFO":logging.INFO,
                    "WARNING": logging.WARNING, "ERROR": logging.ERROR,
                    "CRITICAL": logging.CRITICAL}[args.logging_level.upper()]
        else:
            _logging_level = int(args.logging_level)
        logging.getLogger().setLevel(_logging_level)
    else:
        logging.getLogger().setLevel(logging.WARNING)

    validate_args(args)
```

The printed line:
```config.yaml loaded. We expect this to be ,,train'' : inference```

Which means still you use config.yaml but only changed the value of the key ,,type'' into inference.

**Comment by stevenwalton** [comment]
I'm not sure I completely follow. But I think I introduced an error or hydra changed. I'll get this resolved for you tomorrow (it is after midnight here and even later for Ali). 

In the mean time:

`validate_args` isn't necessary but removing it won't solve this specific problem. Either modify `conf/config.py` to have `inference.batch_size` or I believe `python main.py type=inference +inference.batch_size=1` should work (`+` will add any missing parameters). If there's other missing parameters this same method should work. 

I think the robust method is (copy pasted from a different project)
```
from omegaconf import OmegaConf, open_dict

def check_and_set_hydra(args, key : str, value : Any) -> None:
    if hasattr(args, key):
        args['key'] = value
    else:
        with open_dict(args):
            args['key'] = value
    logging.info(f"{args}.{key} = {value}")
```
I'll validate this tomorrow and check for other issues. Please let us know if you find anything else.

**Comment by justin4ai** [comment]
Dear Steven,

I really appreciate your quick help!! I am looking forward to hearing from you again. Thanks for the hard work ◡̈

**Comment by justin4ai** [comment]
And also I'll be so glad if you let me know what **rpb** stands for. I've seen that keyword in your code but have no clue :(

**Comment by stevenwalton** [comment]
RPB stands for [Relative Positional Encoding](https://jaketae.github.io/study/relative-positional-encoding/), which you can see [here](https://github.com/SHI-Labs/StyleNAT/blob/main/models/stylenat.py#L61). It's worth reading about this and there are some new ones that are even better. 

I apologize for the fix taking so long. I have a unique skill for finding NATTEN compile issues lol.

In the mean time I created a draft pull request (#17) that you can use and _should_ work? But I can't test it properly. I'm sorry about this.

**Pull request merged**
